# Generated by Django 5.1.1 on 2025-10-30 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faunas',
            fields=[
                ('id_fauna', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'faunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Floras',
            fields=[
                ('id_flora', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'floras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('leyenda', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('is_carrusel', models.TextField()),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parques',
            fields=[
                ('id_parque', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parrafos',
            fields=[
                ('id_parrafo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('numero_parrafo', models.IntegerField()),
            ],
            options={
                'db_table': 'parrafos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaunasHasParques',
            fields=[
                ('id_fauna', models.OneToOneField(db_column='id_fauna', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.faunas')),
            ],
            options={
                'db_table': 'faunas_has_parques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParquesFloras',
            fields=[
                ('id_parque', models.OneToOneField(db_column='id_parque', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.parques')),
            ],
            options={
                'db_table': 'parques_floras',
                'managed': False,
            },
        ),
    ]
