# Generated by Django 5.1.1 on 2025-11-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faunas',
            fields=[
                ('id_fauna', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'faunas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Floras',
            fields=[
                ('id_flora', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'floras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parques',
            fields=[
                ('id_parque', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parques',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('leyenda', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('is_carrusel', models.TextField()),
                ('id_fauna', models.ForeignKey(db_column='id_fauna', on_delete=django.db.models.deletion.DO_NOTHING, to='app.faunas')),
                ('id_flora', models.ForeignKey(db_column='id_flora', on_delete=django.db.models.deletion.DO_NOTHING, to='app.floras')),
                ('id_parque', models.ForeignKey(db_column='id_parque', on_delete=django.db.models.deletion.DO_NOTHING, to='app.parques')),
            ],
            options={
                'db_table': 'imagenes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parrafos',
            fields=[
                ('id_parrafo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('numero_de_parrafo', models.IntegerField(blank=True, null=True)),
                ('id_fauna', models.ForeignKey(db_column='id_fauna', on_delete=django.db.models.deletion.DO_NOTHING, to='app.faunas')),
                ('id_flora', models.ForeignKey(db_column='id_flora', on_delete=django.db.models.deletion.DO_NOTHING, to='app.floras')),
                ('id_parque', models.ForeignKey(db_column='id_parque', on_delete=django.db.models.deletion.DO_NOTHING, to='app.parques')),
            ],
            options={
                'db_table': 'parrafos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaunasHasParques',
            fields=[
                ('id_fauna', models.OneToOneField(db_column='id_fauna', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.faunas')),
                ('id_parque', models.ForeignKey(db_column='id_parque', on_delete=django.db.models.deletion.DO_NOTHING, to='app.parques')),
            ],
            options={
                'db_table': 'faunas_has_parques',
                'managed': True,
                'unique_together': {('id_fauna', 'id_parque')},
            },
        ),
        migrations.CreateModel(
            name='ParquesFloras',
            fields=[
                ('id_parque', models.OneToOneField(db_column='id_parque', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.parques')),
                ('id_flora', models.ForeignKey(db_column='id_flora', on_delete=django.db.models.deletion.DO_NOTHING, to='app.floras')),
            ],
            options={
                'db_table': 'parques_floras',
                'managed': True,
                'unique_together': {('id_parque', 'id_flora')},
            },
        ),
    ]
