# Generated by Django 5.1.1 on 2025-11-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_djangomigrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parrafos',
            options={},
        ),
    ]
