# Generated by Django 5.1.1 on 2025-11-01 23:50

from django.db import migrations,models

ROLES = [
    ('user', 'User'),
    ('admin', 'Admin'),
]
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20251101_1656'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='Usuarios',
            name='rol',
            field = models.CharField(max_length=10, choices=ROLES, default='user')
        )
    ]
